language: node_js

node_js:
  - 4
  - 5

env:
  - DB_NAME=hapiness DB_HOST=localhost DB_PORT=27017 JWT=awesomeSecretKeyHere

services:
  - mongodb

after_script:
  - npm run cover

cache:
  directories:
      - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b98f41fd6ac7d5740632
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
